os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - echo "DEVELOPMENT-SNAPSHOT-2016-02-25-a" > .swift-version
  - curl -sL https://gist.github.com/kylef/5c0475ff02b7c7671d2a/raw/621ef9b29bbb852fdfd2e10ed147b321d792c1e4/swiftenv-install.sh | bash
script:
  - . ~/.swiftenv/init
  - Utilities/bootstrap
  - .build/bin/swift-test
notifications:
  email:
    on_success: never
    on_failure: change
